specVersion: 1.0.0
name: testnet-subql-myriad
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=1.13.3"
  query:
    name: "@subql/query"
    version: "*"
description: This project can be use as a starting po...
repository: https://github.com/octopus-appchains/testnet-subql-myriad.git
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://gateway.testnet.octopus.network/myriad/8f543a1c219f14d83c0faedefdd5be6e
  genesisHash: "0x7d45920ff7956e45ef6107720e41b1cfdbd0a50371d6e9072f67070fb285fe16"
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
